### ISSUE TITLE
Using ofxKinectForWindows2 and ofxFlowTools

### ISSUE THREAD

**Issue by rootux** [moostrik/ofxFlowTools#11]
I've tried combining [ofxKinectForWindows2](https://github.com/elliotwoods/ofxKinectForWindows2) and ofxFlowTools to read data from the kinect camera.
https://github.com/rootux/visionquest
I'm calling the kinect like so:
`kinect.getColorSource()->draw(0, 0, cameraFbo.getWidth(), cameraFbo.getHeight());`
I've tried the IR and the depth - all seem to be drawing the camera OK **without **going through the filters (see attached [Image](http://i.imgur.com/NU0PK9Y.jpg) )

What am I missing?

**Comment by shenberg** [comment]
Okay, I got a windows pc and spent time debugging this and found the issue (this applies to the various closed issues on windows/linux):

@moostrik ftOpticalFlowShader.h was broken in [commit d7e723b](https://github.com/moostrik/ofxFlowTools/commit/d7e723b0d464a28a5e4f6dc5a798452aa4457d39) - specifically `flow = normalize(flow) * vec2(strength);` with flow starting as (0,0) will result in flow being either (NaN, NaN) or (Infinity, Infinity). For some reason, on mac when you read nan/infinity from a float texture you get 0 (from Nvidia at least, I've seen forum posts about intel returning nan/inf properly), while in win/linux you get nan/infinty.

Once you get invalid FP values they propagate through the system and poison all the textures due to everything being feedback-based.

**Comment by moostrik** [comment]
wow, this clarifies a lot!
Thanks
